### PR TITLE
Tweak index.md

### PR DESCRIPTION
**Pull request by kingthorin**
Use markdown syntax and update "pitch"

### CODE REVIEW

**Comment by kingthorin** [comment]
Anyone out there?

**Comment by kingthorin** [comment]
@adeyosemanputra 😉

**Comment by kingthorin** [comment]
Is this project dead?

**Comment by adeyosemanputra** [comment]
> Is this project dead?

nope bro still active

**Comment by adeyosemanputra** [comment]
just bussy work with other project

**Review by adeyosemanputra — APPROVED** [review]

**Pull request merged**
